#cloud-config
 
rancher:
network:
interfaces:
eth0:
address: 192.168.1.198/24
gateway: 192.168.1.1
dhcp: false
dns:
nameservers:
- 192.168.1.1
- 8.8.8.8
 
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+kptAVaiJlRnCXNjB0T816LnYFdyReTib0GHBcM1ltw1bGnhLyoNLS3UJ2vgpEDnoWNovnaSSG2P4M0GDzW++i/bYBeNbra0eCxHvjzlil8/jKHhLBGaV4ww+J0L1Aazkp3jTqaRTKLiqPR27fupe1pdiIgsitCxLF5qiYMwdpLXYqFyXRE3b9XBgtkIuDwBbu0vka47i84tp9CAltSlSh2EP9D9YJo8OY2jsz9nOXskThC1GkBsvIAKfeEg+48nPggdjQ/vVrOjF8QCgffWJezSSZndx99cF6R26JckcAtXkWWV1BGeiFh+PvffMgmP6bwTX7SbwDPEOpX+FHr78PFHvEQJC55a0785UQZZuHrmHOoX+dmqIfWOzInvP5S5ABgtiUBe57OMmqcl8D7VFlQWBruaMxQV1fVwDR/EeoexccUjs6czikpszI988vK4DnmW3V1ZnEbQLLRD0lC5rS+Fun6egFCQEPupT7MMuZWn3W3tvZrBhbdwk6Q2Ow3U= Joseph@Josephs-Desktop
